version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/premium-reporting.db
    volumes:
      - ./backend:/app
      - backend-data:/app/data
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: alpine:latest
    command: sh -c "mkdir -p /data && tail -f /dev/null"
    volumes:
      - backend-data:/data
    networks:
      - app-network

volumes:
  backend-data:

networks:
  app-network:
    driver: bridge
